### ISSUE TITLE
Merge conflict not resolved, but commit 

### ISSUE THREAD

**Issue by jhavmoeller** [Novicell/novicell-lazyload#9]
In the demo index.html there's a unresolved merge conflict commited. 

<<<<<<< HEAD
    <script src="../node_modules/novicell-debounce/js/novicell.debounce.js"></script>
    <script src="../js/novicell.dynamic-image.js"></script>
    <script>
        window.lazySizesConfig = {
            useWebp: true
        }
    </script>
    <script src="../js/lazy-images.js"></script>
    <script src="../node_modules/lazysizes/lazysizes.min.js"></script>    
=======
    <script src="../dist/demo.umd.js"></script>
>>>>>>> feature/modular-rework

**Comment by Dan9boi** [comment]
seems to be resolved now.
